#!/bin/sh

# Install authorized keys
mkdir -p /root/.ssh
chmod 700 /root/.ssh
cp /mnt/jffs2/ssh/authorized_keys /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys

# Restore persisted dropbear host key (prevents new key on every boot)
JFFS2_KEY=/mnt/jffs2/ssh/host_keys/dropbear_ed25519_host_key
DROPBEAR_KEY=/etc/dropbear/dropbear_ed25519_host_key

mkdir -p /etc/dropbear
if [ -f "$JFFS2_KEY" ]; then
    cp "$JFFS2_KEY" "$DROPBEAR_KEY"
    chmod 600 "$DROPBEAR_KEY"
fi

killall dropbear 2>/dev/null
dropbear -R

# First boot: persist the host key generated by dropbear
if [ ! -f "$JFFS2_KEY" ]; then
    sleep 1
    [ -f "$DROPBEAR_KEY" ] && cp "$DROPBEAR_KEY" "$JFFS2_KEY" && chmod 600 "$JFFS2_KEY"
fi
